### ISSUE TITLE
How to add include paths using clangd server?

### ISSUE THREAD

**Issue by noorwachid** [yegappan/lsp#129]
I have tried adding the clangd arguments with `--enable-config` with `.clangd` in my root project.

`.vimrc`'s content
``` vim
call LspAddServer([
	{
		filetype: ['c', 'cpp'],
		path: '/usr/bin/clangd',
		args: [
			'--enable-config'
		],
		initializationOptions: {
			fallbackFlags: [
				'-std=c++17',
			]
		}
	},
	{
		filetype: ['php'],
		path: '/usr/local/bin/intelephense',
		args: ['--stdio'],
		syncInit: v:true,
	}	
])
```

`.clangd`'s  content
``` yaml
CompileFlags:
  Add:
    - "-std=c++17"
    - "-I."
    - "-I./src"
```

The LSP diagnostic always says "file not found"
